backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "site/content/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Background Color", name: "backgroundcolor", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "New Date", name: "newdate", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "URL", name: "urllink", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image", name: "image1", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post" 
    label: "Post" 
    folder: "site/content/post" 
    create: true 
    fields:
      - {label: "Full Project Name", name: "title", widget: "string"}
      - {label: "TitleBold", name: "titlebold", widget: "string", required: true}
      - {label: "TitleOutline", name: "titlenormal", widget: "string", required: true}
      - {label: "Hero Image", name: "preview", widget: "image", required: true}
        # - {label: "Legal Msg", name: "notice", widget: "string"} 
      - {label: "Legal Msg", name: "notice", widget: "select", options: 
        ["For legal reasons images of work completed cannot be shown", "For legal reasons some images are representational only or blurred", "For legal reasons images of work completed cannot be shown"]}
      - {label: "Project Start Date", name: "date", widget: "datetime"}
      - {label: "Project End Date", name: "newdate", widget: "datetime"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Client Logo", name: "logo", widget: "image"}
      - {label: "Project Role", name: "role", widget: "select", options: 
        ["Software Engineer", "Senior Software Engineer", "UI Developer", Accessibility Specialist", "Front-End Web Developer"], required: true}
      - {label: 'Tags', name: 'tags', widget: 'select', options: 
        ['accessibility', 'cross-browser', 'javascript', 'mentorship', '.net mvc', 'react', 'sharepoint', 'typescript', 'vue'], multiple: true }
      - {label: 'Technology Stack', name: 'technology', widget: 'select', options: 
        ['adobe xd', 'ASP.NET MVC', 'AxE DevTools', 'balsamiq', 'HTML/CSS', 'HTML, SCSS', 'Javascript', 'NVDA', 'React', 'Sharepoint', 'SharePoint SPFx (Framework)', 'SharePoint Workbench', 'TalkBack', 'Typescript', 'VoiceOver', 'vue', 'WAVE'], multiple: true }
      # - {label: "Start time", name: "start", widget: "datetime", default: "", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL", picker_utc: false }
      - {label: "Duration", name: "duration", widget: "text"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Intro Heading", name: "introheading", widget: "string"}
      - {label: "IntroBody", name: "introbody", widget: "markdown"}
      - {label: "Overview Heading", name: "overviewheading", widget: "string"}
      - {label: "Overview Body", name: "overviewbody", widget: "markdown"}
      - {label: Overview icon section, name: introw, widget: object, fields: [{label: Blurbs, name: blurbsw, widget: list, fields: [{label: Image, name: imagew, widget: image}, {label: Text, name: textw, widget: markdown}]}], required: false}
      - {label: "Overview Blurb", name: "overviewblurb", widget: "markdown"}
      - {label: "Purple Section Heading", name: "purplesectionheading", widget: "string"}
      - {label: "Purple Section", name: "purplesection1", widget: "markdown", required: false}
      - {label: "Purple Section (split)", name: "textimagesplitcontent", widget: "markdown", required: false}
      - {label: "Purple Section (split) caption", name: "textimagesplitimagecaption", widget: "string", required: false}
      - {label: "Purple Section 2", name: "purplesection2", widget: "markdown"}
      - {label: "Purple Section Image", name: "image", widget: "image"}
      # - {label: "Background Color", name: "backgroundcolor", widget: "string"}       
      # - {label: "URL", name: "urllink", widget: "text"}
      # - {label: "Favorite", name: "favorite", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image1", name: "image1", widget: "image", required: false}

      # - {label: Intro, name: introw, widget: object, fields: [{label: Blurbs, name: blurbsw, widget: list, fields: [{label: Image, name: imagew, widget: image}, {label: Text, name: textw, widget: markdown}]}]}

      - label: 'Typed List'
        name: 'typed_list2'
        widget: 'list'
        types:
          - label: 'Text with scrolling image'
            name: 'text_with_scroll_img'
            widget: 'object'
            fields:
              - { label: 'String', name: 'heading', widget: 'string' }
              - { label: 'Text', name: 'left_side_text', widget: 'markdown' }
              - { label: 'Full width image', name: 'fullwidth', widget: 'boolean'}
              - { label: "Image", name: "image", widget: "image"}
              - { label: 'Image caption', name: 'caption', widget: 'string' }
              - { label: 'Blurb', name: 'blurb', widget: 'markdown' }
              - { label: 'Text', name: 'full_width_text', widget: 'markdown' }
              - { label: "Decorative Image", name: "decorative_image", widget: "image", required: false}
          - label: 'icon sections on left, image on right'
            name: 'type_2_object'
            widget: 'object'
            fields:
              - {label: Intro, name: introw, widget: object, fields: [{label: Blurbs, name: blurbsw, widget: list, fields: [{label: Image, name: imagew, widget: image}, {label: Text, name: textw, widget: markdown}]}]}
              - { label: 'Image', name: 'image1', widget: 'image' }
              - { label: 'Caption', name: 'image1caption', widget: 'string' }
              - { label: 'Image', name: 'image2', widget: 'image' }
              - { label: 'Caption', name: 'image2caption', widget: 'string' }
              - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
          - label: 'heading_markdown'
            name: 'heading_markdown'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'markdown', name: 'markdown', widget: 'markdown' }
              - {label: Intro, name: introw, widget: object, fields: [{label: Blurbs, name: blurbsw, widget: list, fields: [{label: Image, name: imagew, widget: image}, {label: Text, name: textw, widget: markdown}]}]}
              - { label: 'markdown optional', name: 'markdown_optional', widget: 'markdown' }
          - label: 'text and image split'
            name: 'type_4_object'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'markdown', name: 'textimagesplitcontent', widget: 'markdown' }
              - { label: 'caption', name: 'textimagesplitimagecaption', widget: 'string' }  
              - { label: 'markdown reverse', name: 'textimagesplitcontentreverse', widget: 'markdown' }
              - { label: 'caption reverse', name: 'textimagesplitreverseimagecaption', widget: 'string' }    
          - label: 'stacked image with text'
            name: 'type_5_object'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'markdown', name: 'markdown', widget: 'markdown' }
              - { label: 'Image1', name: 'image1', widget: 'image' }
              - { label: 'Image1', name: 'image2', widget: 'image' }
              - { label: 'caption', name: 'caption', widget: 'string' }                         
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Background Color", name: "backgroundcolor", widget: "string"}
          # - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Text, name: text, widget: markdown}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Image List Heading", name: image_list_heading, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string}]}          
          - {label: "Image List", name: image_list, widget: list, fields: [              
              {label: "Image", name: "image", widget: "image"},
              {label: "Link Text", name: "linktext", widget: "text"},
              {label: "Link URL", name: "linkurl", widget: "string"},
              {label: "Link Text 2", name: "linktext2", widget: "text", required: false},
              {label: "Link URL 2", name: "linkurl2", widget: "string", required: false},
              {label: "Description", name: "text", widget: "text"},
              {label: "Description 2", name: "text2", widget: "text", required: false},
              {label: "Description 3", name: "text3", widget: "text", required: false}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Background Color", name: "backgroundcolor", widget: "string"}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: "Background Color", name: "backgroundcolor", widget: "string"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
